server:
  port: 8080

spring:
  application:
    name: canary-test-gateway
  cloud:
    gateway:
      routes:
        - id: creditcheck_v1
          uri: http://localhost:8081/
          predicates:
            - Path=/creditcheck
            - ConditionalHeaderPredicateFactory=x-account-key, !endsWith(1 2)
          filters:
            - RewritePath=/(?<segment>.*), /v1/$\{segment}

        - id: creditcheck_v2
          uri: http://localhost:8081/
          predicates:
            - Path=/creditcheck
            - ConditionalHeaderPredicateFactory=x-account-key, endsWith(1 2)
          filters:
            - RewritePath=/(?<segment>.*), /v2/$\{segment}
