server:
  port: 8080

spring:
  application:
    name: canary-test-gateway
  cloud:
    gateway:
      routes:
        # Custom conditional header predicate
        - id: creditcheck_piloting_v1
          uri: http://localhost:8081/
          predicates:
            - Path=/creditcheck
            - ConditionalHeaderPredicateFactory=x-account-key, !endsWith(1 2)
          filters:
            - RewritePath=/(?<segment>.*), /v1/$\{segment}

        - id: creditcheck_piloting_v2
          uri: http://localhost:8081/
          predicates:
            - Path=/creditcheck
            - ConditionalHeaderPredicateFactory=x-account-key, endsWith(1 2)
          filters:
            - RewritePath=/(?<segment>.*), /v2/$\{segment}

        # Built-in percentage based routing
        - id: creditcheck_percentage_v1
          uri: http://localhost:8081/
          predicates:
            - Path=/creditcheckpct
            - Weight=service1, 90
          filters:
            - RewritePath=/creditcheckpct(?<segment>.*), /v1/creditcheck$\{segment}

        - id: creditcheck_percentage_v2
          uri: http://localhost:8081/
          predicates:
            - Path=/creditcheckpct
            - Weight=service1, 10
          filters:
            - RewritePath=/creditcheckpct(?<segment>.*), /v2/creditcheck$\{segment}

